### ISSUE TITLE
use Large images 768*1024

### ISSUE THREAD

**Issue by seekingdeep** [JCruan519/MALUNet#2]
Peace be upon you
What are your thoughts when wanting to train and predict on large images such as 768*1024

**Comment by JCruan519** [comment]
> Peace be upon you What are your thoughts when wanting to train and predict on large images such as 768*1024

Hello, thank you for your interest in this work. Firstly, using large images for training should result in better performance, as they contain more information than downsampled images. Secondly, in tasks such as retinal or cell image segmentation, researchers often partition large images into small patches for training instead of directly downsampling the image size. Therefore, for your question, you can try using the approach of partitioning small patches for processing.
